<?php

/**
*	@Desenvolvido por Afixo Agência WEB
*	@url www.afixo.com.br
*	@email gestor@afixo.com.br
*
*	@autor Flávio Silva Brandão <flavio@afixo.com.br>
*	@version 11-03-2016 as 15:39:25
*/

class ConveniosProgramas extends DB {

	private $tabela = 'convenios_programas';
	private $ANO_CONVENIO;
	private $NR_CONVENIO;
	private $ANO_PROPOSTA;
	private $NR_PROPOSTA;
	private $TX_MODALIDADE;
	private $TX_SITUACAO;
	private $TX_SUBSITUACAO;
	private $CD_ORGAO_SUPERIOR;
	private $NM_ORGAO_SUPERIOR;
	private $CD_ORGAO_CONCEDENTE;
	private $TX_ESFERA_ADM_PROPONENTE;
	private $TX_REGIAO_PROPONENTE;
	private $UF_PROPONENTE;
	private $NM_MUNICIPIO_PROPONENTE;
	private $CD_IDENTIF_PROPONENTE;
	private $NM_PROPONENTE;
	private $NM_ORGAO_CONCEDENTE;
	private $DT_INCLUSAO_PROPOSTA;
	private $CD_PROGRAMA;
	private $NM_PROGRAMA;
	private $CD_ACAO_PPA;
	private $DT_INICIO_VIGENCIA;
	private $DT_FIM_VIGENCIA;
	private $DT_ASSINATURA_CONVENIO;
	private $MES_ASSINATURA_CONVENIO;
	private $ANO_ASSINATURA_CONVENIO;
	private $MES_PUBLICACAO_CONVENIO;
	private $ANO_PUBLICACAO_CONVENIO;
	private $DT_PUBLICACAO;
	private $DT_ULTIMO_EMPENHO;
	private $DT_ULTIMO_PGTO;
	private $VL_GLOBAL;
	private $VL_REPASSE;
	private $VL_CONTRAPARTIDA_TOTAL;
	private $VL_CONTRAPARTIDA_FINANC;
	private $VL_CONTRAPARTIDA_BENS_SERV;
	private $VL_DESEMBOLSADO;
	private $VL_EMPENHADO;
	private $TX_OBJETO_CONVENIO;
	private $TX_JUSTIFICATIVA;
	private $TX_ENDERECO_PROPONENTE;
	private $TX_BAIRRO_PROPONENTE;
	private $NR_CEP_PROPONENTE;
	private $NM_RESPONS_PROPONENTE;
	private $CD_RESPONS_PROPONENTE;
	private $TX_CARGO_RESPONS_PROPONENTE;
	private $NM_RESPONS_CONCEDENTE;
	private $CD_RESPONS_CONCEDENTE;
	private $TX_CARGO_RESPONS_CONCEDENTE;
	private $TX_SITUACAO_PUBLICACAO;
	private $NR_PROCESSO_CONVENIO;
	private $NR_INTERNO_CONVENIO;
	private $IN_ASSINADO_SN;
	private $IN_ADITIVO_SN;
	private $IN_PUBLICADO_SN;
	private $IN_EMPENHADO_SN;
	private $IN_PRORROGA_OFICIO_SN;
	private $IN_PERMITE_AJUSTE_CRON_FISICO;
	private $QT_EMPENHOS;
	private $QT_ADITIVOS;
	private $QT_PRORROGAS;
	private $TX_QUALIFIC_PROPONENTE;
	private $ID_CONVENIO;
	private $ID_PROP;
	private $ID_PROP_PROGRAMA;

	/**
	* Método construtor do objeto convenios_programas  
	 @param string ANO_CONVENIO
	 @param inteiro NR_CONVENIO
	 @param inteiro ANO_PROPOSTA
	 @param inteiro NR_PROPOSTA
	 @param string TX_MODALIDADE
	 @param string TX_SITUACAO
	 @param string TX_SUBSITUACAO
	 @param inteiro CD_ORGAO_SUPERIOR
	 @param string NM_ORGAO_SUPERIOR
	 @param inteiro CD_ORGAO_CONCEDENTE
	 @param string TX_ESFERA_ADM_PROPONENTE
	 @param string TX_REGIAO_PROPONENTE
	 @param string UF_PROPONENTE
	 @param string NM_MUNICIPIO_PROPONENTE
	 @param bigint CD_IDENTIF_PROPONENTE
	 @param string NM_PROPONENTE
	 @param string NM_ORGAO_CONCEDENTE
	 @param string DT_INCLUSAO_PROPOSTA
	 @param bigint CD_PROGRAMA
	 @param string NM_PROGRAMA
	 @param string CD_ACAO_PPA
	 @param string DT_INICIO_VIGENCIA
	 @param string DT_FIM_VIGENCIA
	 @param string DT_ASSINATURA_CONVENIO
	 @param string MES_ASSINATURA_CONVENIO
	 @param string ANO_ASSINATURA_CONVENIO
	 @param string MES_PUBLICACAO_CONVENIO
	 @param string ANO_PUBLICACAO_CONVENIO
	 @param string DT_PUBLICACAO
	 @param string DT_ULTIMO_EMPENHO
	 @param string DT_ULTIMO_PGTO
	 @param string VL_GLOBAL
	 @param string VL_REPASSE
	 @param string VL_CONTRAPARTIDA_TOTAL
	 @param string VL_CONTRAPARTIDA_FINANC
	 @param string VL_CONTRAPARTIDA_BENS_SERV
	 @param string VL_DESEMBOLSADO
	 @param string VL_EMPENHADO
	 @param string TX_OBJETO_CONVENIO
	 @param string TX_JUSTIFICATIVA
	 @param string TX_ENDERECO_PROPONENTE
	 @param string TX_BAIRRO_PROPONENTE
	 @param string NR_CEP_PROPONENTE
	 @param string NM_RESPONS_PROPONENTE
	 @param string CD_RESPONS_PROPONENTE
	 @param string TX_CARGO_RESPONS_PROPONENTE
	 @param string NM_RESPONS_CONCEDENTE
	 @param string CD_RESPONS_CONCEDENTE
	 @param string TX_CARGO_RESPONS_CONCEDENTE
	 @param string TX_SITUACAO_PUBLICACAO
	 @param string NR_PROCESSO_CONVENIO
	 @param string NR_INTERNO_CONVENIO
	 @param string IN_ASSINADO_SN
	 @param string IN_ADITIVO_SN
	 @param string IN_PUBLICADO_SN
	 @param string IN_EMPENHADO_SN
	 @param string IN_PRORROGA_OFICIO_SN
	 @param string IN_PERMITE_AJUSTE_CRON_FISICO
	 @param string QT_EMPENHOS
	 @param string QT_ADITIVOS
	 @param string QT_PRORROGAS
	 @param string TX_QUALIFIC_PROPONENTE
	 @param inteiro ID_CONVENIO
	 @param inteiro ID_PROP
	 @param inteiro ID_PROP_PROGRAMA

	**/
	public function __construct($ANO_CONVENIO="",$NR_CONVENIO="",$ANO_PROPOSTA="",$NR_PROPOSTA="",$TX_MODALIDADE="",$TX_SITUACAO="",$TX_SUBSITUACAO="",$CD_ORGAO_SUPERIOR="",$NM_ORGAO_SUPERIOR="",$CD_ORGAO_CONCEDENTE="",$TX_ESFERA_ADM_PROPONENTE="",$TX_REGIAO_PROPONENTE="",$UF_PROPONENTE="",$NM_MUNICIPIO_PROPONENTE="",$CD_IDENTIF_PROPONENTE="",$NM_PROPONENTE="",$NM_ORGAO_CONCEDENTE="",$DT_INCLUSAO_PROPOSTA="",$CD_PROGRAMA="",$NM_PROGRAMA="",$CD_ACAO_PPA="",$DT_INICIO_VIGENCIA="",$DT_FIM_VIGENCIA="",$DT_ASSINATURA_CONVENIO="",$MES_ASSINATURA_CONVENIO="",$ANO_ASSINATURA_CONVENIO="",$MES_PUBLICACAO_CONVENIO="",$ANO_PUBLICACAO_CONVENIO="",$DT_PUBLICACAO="",$DT_ULTIMO_EMPENHO="",$DT_ULTIMO_PGTO="",$VL_GLOBAL="",$VL_REPASSE="",$VL_CONTRAPARTIDA_TOTAL="",$VL_CONTRAPARTIDA_FINANC="",$VL_CONTRAPARTIDA_BENS_SERV="",$VL_DESEMBOLSADO="",$VL_EMPENHADO="",$TX_OBJETO_CONVENIO="",$TX_JUSTIFICATIVA="",$TX_ENDERECO_PROPONENTE="",$TX_BAIRRO_PROPONENTE="",$NR_CEP_PROPONENTE="",$NM_RESPONS_PROPONENTE="",$CD_RESPONS_PROPONENTE="",$TX_CARGO_RESPONS_PROPONENTE="",$NM_RESPONS_CONCEDENTE="",$CD_RESPONS_CONCEDENTE="",$TX_CARGO_RESPONS_CONCEDENTE="",$TX_SITUACAO_PUBLICACAO="",$NR_PROCESSO_CONVENIO="",$NR_INTERNO_CONVENIO="",$IN_ASSINADO_SN="",$IN_ADITIVO_SN="",$IN_PUBLICADO_SN="",$IN_EMPENHADO_SN="",$IN_PRORROGA_OFICIO_SN="",$IN_PERMITE_AJUSTE_CRON_FISICO="",$QT_EMPENHOS="",$QT_ADITIVOS="",$QT_PRORROGAS="",$TX_QUALIFIC_PROPONENTE="",$ID_CONVENIO="",$ID_PROP="",$ID_PROP_PROGRAMA="") {
		$this->ANO_CONVENIO = $ANO_CONVENIO;
		$this->NR_CONVENIO = $NR_CONVENIO;
		$this->ANO_PROPOSTA = $ANO_PROPOSTA;
		$this->NR_PROPOSTA = $NR_PROPOSTA;
		$this->TX_MODALIDADE = $TX_MODALIDADE;
		$this->TX_SITUACAO = $TX_SITUACAO;
		$this->TX_SUBSITUACAO = $TX_SUBSITUACAO;
		$this->CD_ORGAO_SUPERIOR = $CD_ORGAO_SUPERIOR;
		$this->NM_ORGAO_SUPERIOR = $NM_ORGAO_SUPERIOR;
		$this->CD_ORGAO_CONCEDENTE = $CD_ORGAO_CONCEDENTE;
		$this->TX_ESFERA_ADM_PROPONENTE = $TX_ESFERA_ADM_PROPONENTE;
		$this->TX_REGIAO_PROPONENTE = $TX_REGIAO_PROPONENTE;
		$this->UF_PROPONENTE = $UF_PROPONENTE;
		$this->NM_MUNICIPIO_PROPONENTE = $NM_MUNICIPIO_PROPONENTE;
		$this->CD_IDENTIF_PROPONENTE = $CD_IDENTIF_PROPONENTE;
		$this->NM_PROPONENTE = $NM_PROPONENTE;
		$this->NM_ORGAO_CONCEDENTE = $NM_ORGAO_CONCEDENTE;
		$this->DT_INCLUSAO_PROPOSTA = $DT_INCLUSAO_PROPOSTA;
		$this->CD_PROGRAMA = $CD_PROGRAMA;
		$this->NM_PROGRAMA = $NM_PROGRAMA;
		$this->CD_ACAO_PPA = $CD_ACAO_PPA;
		$this->DT_INICIO_VIGENCIA = $DT_INICIO_VIGENCIA;
		$this->DT_FIM_VIGENCIA = $DT_FIM_VIGENCIA;
		$this->DT_ASSINATURA_CONVENIO = $DT_ASSINATURA_CONVENIO;
		$this->MES_ASSINATURA_CONVENIO = $MES_ASSINATURA_CONVENIO;
		$this->ANO_ASSINATURA_CONVENIO = $ANO_ASSINATURA_CONVENIO;
		$this->MES_PUBLICACAO_CONVENIO = $MES_PUBLICACAO_CONVENIO;
		$this->ANO_PUBLICACAO_CONVENIO = $ANO_PUBLICACAO_CONVENIO;
		$this->DT_PUBLICACAO = $DT_PUBLICACAO;
		$this->DT_ULTIMO_EMPENHO = $DT_ULTIMO_EMPENHO;
		$this->DT_ULTIMO_PGTO = $DT_ULTIMO_PGTO;
		$this->VL_GLOBAL = $VL_GLOBAL;
		$this->VL_REPASSE = $VL_REPASSE;
		$this->VL_CONTRAPARTIDA_TOTAL = $VL_CONTRAPARTIDA_TOTAL;
		$this->VL_CONTRAPARTIDA_FINANC = $VL_CONTRAPARTIDA_FINANC;
		$this->VL_CONTRAPARTIDA_BENS_SERV = $VL_CONTRAPARTIDA_BENS_SERV;
		$this->VL_DESEMBOLSADO = $VL_DESEMBOLSADO;
		$this->VL_EMPENHADO = $VL_EMPENHADO;
		$this->TX_OBJETO_CONVENIO = $TX_OBJETO_CONVENIO;
		$this->TX_JUSTIFICATIVA = $TX_JUSTIFICATIVA;
		$this->TX_ENDERECO_PROPONENTE = $TX_ENDERECO_PROPONENTE;
		$this->TX_BAIRRO_PROPONENTE = $TX_BAIRRO_PROPONENTE;
		$this->NR_CEP_PROPONENTE = $NR_CEP_PROPONENTE;
		$this->NM_RESPONS_PROPONENTE = $NM_RESPONS_PROPONENTE;
		$this->CD_RESPONS_PROPONENTE = $CD_RESPONS_PROPONENTE;
		$this->TX_CARGO_RESPONS_PROPONENTE = $TX_CARGO_RESPONS_PROPONENTE;
		$this->NM_RESPONS_CONCEDENTE = $NM_RESPONS_CONCEDENTE;
		$this->CD_RESPONS_CONCEDENTE = $CD_RESPONS_CONCEDENTE;
		$this->TX_CARGO_RESPONS_CONCEDENTE = $TX_CARGO_RESPONS_CONCEDENTE;
		$this->TX_SITUACAO_PUBLICACAO = $TX_SITUACAO_PUBLICACAO;
		$this->NR_PROCESSO_CONVENIO = $NR_PROCESSO_CONVENIO;
		$this->NR_INTERNO_CONVENIO = $NR_INTERNO_CONVENIO;
		$this->IN_ASSINADO_SN = $IN_ASSINADO_SN;
		$this->IN_ADITIVO_SN = $IN_ADITIVO_SN;
		$this->IN_PUBLICADO_SN = $IN_PUBLICADO_SN;
		$this->IN_EMPENHADO_SN = $IN_EMPENHADO_SN;
		$this->IN_PRORROGA_OFICIO_SN = $IN_PRORROGA_OFICIO_SN;
		$this->IN_PERMITE_AJUSTE_CRON_FISICO = $IN_PERMITE_AJUSTE_CRON_FISICO;
		$this->QT_EMPENHOS = $QT_EMPENHOS;
		$this->QT_ADITIVOS = $QT_ADITIVOS;
		$this->QT_PRORROGAS = $QT_PRORROGAS;
		$this->TX_QUALIFIC_PROPONENTE = $TX_QUALIFIC_PROPONENTE;
		$this->ID_CONVENIO = $ID_CONVENIO;
		$this->ID_PROP = $ID_PROP;
		$this->ID_PROP_PROGRAMA = $ID_PROP_PROGRAMA;
	}

	public function retornar($id, $campo = 'id', $tabela = 'convenios_programas', $ordenadoPor = '', $order = '', $limit = '') {
		return parent::retornar($id, $campo, $tabela, $ordenadoPor, $order, $limit);
	}

	public function inserir($objeto, $tabela = 'convenios_programas') {
		return parent::inserir($objeto, $tabela);
	}

	public function editar($objeto, $campo = 'id', $tabela = 'convenios_programas') {
		return parent::editar($objeto, $campo, $tabela);
	}

	public function excluir($valor, $campo = 'id', $tabela = 'convenios_programas'){
		return parent::excluir($valor, $campo, $tabela);
	}

}
?>